<a href="https://colab.research.google.com/github/Hadeersamirr/ML/blob/main/Linear_Regression_Multiple_Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [200]:
import pandas as pd
import numpy  as np
# sklearn standfor Science Kit Learn
from sklearn import linear_model
import matplotlib.pyplot as plt


In [203]:
df = pd.read_csv('/content/homepricesmulti.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [205]:
#replace the NAN value with median
df.bedrooms.median()

4.0

In [206]:
df.bedrooms.fillna(df.bedrooms.median(),inplace=True)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [208]:
x= df.drop('price' ,axis='columns')
x

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [210]:
y=df.price
y

0    550000
1    565000
2    610000
3    595000
4    760000
5    810000
Name: price, dtype: int64

In [211]:
model=linear_model.LinearRegression()

In [212]:
model.fit(x,y)

LinearRegression()

**y = mx1 + m2x2 + m3x3 + c **

In [214]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [215]:
model.intercept_

221323.00186540396

Find the price of home with 3000 sqr ft area ,3 bedrooms, 40 years old

In [216]:
model.predict([[3000,3,40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [218]:
model.predict([[3000,4,40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([521797.13165825])

In [219]:
112.06244194*3000 +23388.88007794*3 + -3231.71790863*40 +221323.00186540396


498408.251574024

Find price of home with 2500 sqr ft area ,4 bedrooms and 5 years

In [220]:
model.predict([[2500, 4 ,5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [222]:
model.predict([[2500, 4 ,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([595034.6270325])

In [224]:
model.score(x,y)

0.9550196399325821